idf_component_register(SRCS
"main.c"
"bsp/bsp_board.c"
"bsp/bsp_wifi.c"
"bsp/bsp_codec.c"
"bsp/bsp_lcd.c"
"bsp/bsp_touch.c"
"bsp/bsp_servo.c"
"bsp/servo_manager.c"
"wake_word/custom_wake_word.c"
"protocol/mqtt_protocol.c"
"protocol/websocket_client.c"
"audio/audio_processor.c"
"audio/audio_encoder.c"
"audio/audio_decoder.c"
"session/session.c"
"application.c"
"protocol/auth.c"
"ui/interaction.c"
"ui/reminder.c"
"ui/ui_port.c"
"ui/flash.c"
"ui/games.c"
"ui/font_cn_16.c"
"test_wifi_time.c"
INCLUDE_DIRS "."
)
